import { invitationInterface } from "interfaces/networkInterfaces";
export const invitationsResponse: invitationInterface[] = [
    {
      profilePicture: "src/assets/Tyrone.jpg",
      userName: "Ben allen",
      userBio: "Frontend Developer at Tech Inc.",
      Mutuals: "5 mutual connections",
      ignoreButtonid: "ignore-1",
      acceptButtonid: "accept-1",
    },
    {
      profilePicture: "src/assets/Tyrone.jpg",
      userName: "Abdelrahman Sakr",
      userBio: "UI/UX Designer at Design Studio",
      Mutuals: "2 mutual connections",
      ignoreButtonid: "ignore-2",
      acceptButtonid: "accept-2",
    },
    {
        profilePicture: "src/assets/Tyrone.jpg",
        userName: "Abdelrahman Fathy",
        userBio: "Mobile Developer at Monster Inc.",
        Mutuals: "2 mutual connections",
        ignoreButtonid: "ignore-3",
        acceptButtonid: "accept-3",
      },
      {
        profilePicture: "src/assets/Tyrone.jpg",
        userName: "Ben allen",
        userBio: "Frontend Developer at Tech Inc.",
        Mutuals: "5 mutual connections",
        ignoreButtonid: "ignore-1",
        acceptButtonid: "accept-1",
      },
      {
        profilePicture: "src/assets/Tyrone.jpg",
        userName: "Ben allen",
        userBio: "Frontend Developer at Tech Inc.",
        Mutuals: "5 mutual connections",
        ignoreButtonid: "ignore-1",
        acceptButtonid: "accept-1",
      },
      {
        profilePicture: "src/assets/Tyrone.jpg",
        userName: "Ben allen",
        userBio: "Frontend Developer at Tech Inc.",
        Mutuals: "5 mutual connections",
        ignoreButtonid: "ignore-1",
        acceptButtonid: "accept-1",
      },
      {
        profilePicture: "src/assets/Tyrone.jpg",
        userName: "Ben allen",
        userBio: "Frontend Developer at Tech Inc.",
        Mutuals: "5 mutual connections",
        ignoreButtonid: "ignore-1",
        acceptButtonid: "accept-1",
      },
      {
        profilePicture: "src/assets/Tyrone.jpg",
        userName: "Ben allen",
        userBio: "Frontend Developer at Tech Inc.",
        Mutuals: "5 mutual connections",
        ignoreButtonid: "ignore-1",
        acceptButtonid: "accept-1",
      },
  ];